# Creating and Manipulation 2D Arrays

In [4]:
import numpy as np
import pandas as pd

In [6]:
df=pd.read_csv('DS1_C4_S2_Admission_Predict_Practice.csv')
print(df)

     Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
395         396        324          110                  3  3.5   3.5  9.04   
396         397        325          107                  3  3.0   3.5  9.11   
397         398        330          116                  4  5.0   4.5  9.45   
398         399        312          103                  3  3.5   4.0  8.78   
399         400        333          117                  4  5.0   4.0  9.66   

     Research  Chance of Admit   
0           1    

In [2]:
from numpy import genfromtxt
adm=genfromtxt('DS1_C4_S2_Admission_Predict_Practice.csv',delimiter=',',skip_header=1) 
print(adm)

[[  1.   337.   118.   ...   9.65   1.     0.92]
 [  2.   324.   107.   ...   8.87   1.     0.76]
 [  3.   316.   104.   ...   8.     1.     0.72]
 ...
 [398.   330.   116.   ...   9.45   1.     0.91]
 [399.   312.   103.   ...   8.78   0.     0.67]
 [400.   333.   117.   ...   9.66   1.     0.95]]


In [5]:
# Task 1
ind=np.where(adm[:,1]>320)
print('Number of student with GRE score greater then 320: ',np.size(ind))


Number of student with GRE score greater then 320:  163


In [6]:
# Task 2
ind1=np.where(adm[:,2]>110)
print('The admission possibility of those students TOEFL scores greater than 110\n',adm[ind1,8])

The admission possibility of those students TOEFL scores greater than 110
 [[0.92 0.9  0.84 0.78 0.7  0.94 0.95 0.97 0.94 0.91 0.9  0.94 0.87 0.91
  0.86 0.89 0.78 0.78 0.72 0.52 0.55 0.61 0.78 0.94 0.96 0.93 0.72 0.74
  0.96 0.92 0.94 0.86 0.9  0.79 0.74 0.87 0.91 0.93 0.94 0.94 0.85 0.78
  0.84 0.92 0.96 0.79 0.89 0.8  0.9  0.92 0.97 0.8  0.81 0.83 0.96 0.93
  0.94 0.86 0.81 0.89 0.89 0.87 0.85 0.9  0.89 0.93 0.93 0.88 0.9  0.86
  0.94 0.97 0.97 0.95 0.96 0.94 0.93 0.91 0.76 0.71 0.82 0.91 0.88 0.85
  0.86 0.7  0.76 0.77 0.93 0.85 0.9  0.7  0.83 0.89 0.8  0.94 0.93 0.92
  0.89 0.86 0.9  0.71 0.8  0.79 0.8  0.81 0.8  0.8  0.83 0.94 0.93 0.91
  0.86 0.95 0.96 0.96 0.84 0.89 0.91 0.95]]


In [16]:
# Task 3
sort_gre=np.sort(adm[:,1])[-1:-11:-1]
print('The top 10 GRE scores ',sort_gre.T) # least of top 10 GRE score is 339
sort_toefl=np.sort(adm[:,2])[-1:-9:-1]
print('The top 10 TOEFL scores ',sort_toefl.T) # Top 8 TOEFL scores are 120
gre_ind=np.where(adm[:,1]>338)# indexs for the top 10 GRE scores
toefl_ind=np.where(adm[:,2]==120)# indexs for the top 8 TOEFL scores
print('\nData of Top 10 GRE student with serial details:\n',adm[gre_ind,:])
print('\nData of Top 8 TOEFL student with serial details:\n',adm[toefl_ind,:])
print('\nData of Top 10 GRE student serial details:',adm[gre_ind,0])
print('\nData of Top 8 TOEFL student serial details:',adm[toefl_ind,0])

The top 10 GRE scores  [340. 340. 340. 340. 340. 340. 340. 340. 339. 339.]
The top 10 TOEFL scores  [120. 120. 120. 120. 120. 120. 120. 120.]

Data of Top 10 GRE student with serial details:
 [[[ 26.   340.   120.     5.     4.5    4.5    9.6    1.     0.94]
  [ 34.   340.   114.     5.     4.     4.     9.6    1.     0.9 ]
  [ 48.   339.   119.     5.     4.5    4.     9.7    0.     0.89]
  [ 82.   340.   120.     4.     5.     5.     9.5    1.     0.96]
  [ 85.   340.   115.     5.     4.5    4.5    9.45   1.     0.94]
  [131.   339.   114.     5.     4.     4.5    9.76   1.     0.96]
  [144.   340.   120.     4.     4.5    4.     9.92   1.     0.97]
  [149.   339.   116.     4.     4.     3.5    9.8    1.     0.96]
  [203.   340.   120.     5.     4.5    4.5    9.91   1.     0.97]
  [285.   340.   112.     4.     5.     4.5    9.66   1.     0.94]
  [385.   340.   113.     4.     5.     5.     9.74   1.     0.96]]]

Data of Top 8 TOEFL student with serial details:
 [[[ 26.   340.   1

In [26]:
# Task 4
off_ind=np.where((adm[:,1]>300) & (adm[:,1]<305) & (adm[:,4]==3.5) & (adm[:,7]==1))
adm1=adm[off_ind,0]
adm2=adm[off_ind,2]
print('The Serial Number of the students:\n ',adm1)
print('The TOEFL Score of the students:\n ',adm2)
adm3=np.append(adm1,adm2,axis=0)   
print('\nThe Serial Number and TOEFL Score of the students:\n ',adm3.T)

The Serial Number of the students:
  [[113. 210. 358.]]
The TOEFL Score of the students:
  [[107. 104. 104.]]

The Serial Number and TOEFL Score of the students:
  [[113. 107.]
 [210. 104.]
 [358. 104.]]


In [33]:
# Task 5
scholarship=np.random.randint(5000,10001,400)
print('The scholarship amount list:\n',scholarship.T)

The scholarship amount list:
 [5671 9009 8884 7094 6469 9339 8838 9305 7682 9411 7062 9565 7599 7463
 8158 9545 9782 6616 8753 7701 9571 5472 9811 7822 8108 8156 6933 8315
 9531 7146 8916 7350 9142 8882 7985 9546 5660 6613 7179 8573 7300 6619
 9916 8014 9039 8628 5458 8466 8594 7282 8774 9036 7259 7309 6320 6536
 6493 8964 9747 5585 6619 7594 5867 8409 9454 6442 8508 7434 5516 8133
 5595 9231 6635 7246 8426 8385 8364 6106 7263 5093 5526 7173 7361 6214
 7159 6725 8211 8196 8457 9198 5364 6697 7898 8898 7801 7472 9266 7273
 5116 9903 9039 7710 7974 6239 9588 5331 6930 9386 5323 5298 5951 7741
 5713 9284 5224 6103 9507 8725 9173 6216 5930 8891 6256 6700 8322 6014
 9584 9183 9991 6800 9525 6465 6202 9657 8961 5462 7935 8062 9792 5872
 6330 7099 8296 9946 7457 6988 7312 9030 6814 8877 5116 8575 5654 7510
 8326 5366 7432 7065 5240 7097 8087 7364 8631 9987 8825 9395 8312 7994
 9161 6880 8388 9196 7404 5641 6215 7668 9676 7254 7184 9719 9750 8986
 8978 6763 6474 9807 8561 5919 7670 8618 8672 7

In [37]:
sc_ind=np.where(scholarship>9000)
np.count_nonzero(sc_ind)

88

In [41]:
print(adm)
adm=np.insert(adm,9,[scholarship],axis=1)
print('\nThe updated Admission list :\n',adm)
sch_ind=np.where(adm[:,9]>9000)
print('\nThe number of students with scholarship more then $9000: ',np.count_nonzero(sch_ind))

[[1.000e+00 3.370e+02 1.180e+02 ... 5.671e+03 5.671e+03 7.336e+03]
 [2.000e+00 3.240e+02 1.070e+02 ... 9.009e+03 9.009e+03 5.142e+03]
 [3.000e+00 3.160e+02 1.040e+02 ... 8.884e+03 8.884e+03 5.222e+03]
 ...
 [3.980e+02 3.300e+02 1.160e+02 ... 7.402e+03 7.402e+03 8.020e+03]
 [3.990e+02 3.120e+02 1.030e+02 ... 9.711e+03 9.711e+03 7.810e+03]
 [4.000e+02 3.330e+02 1.170e+02 ... 9.154e+03 9.154e+03 9.318e+03]]

The updated Admission list :
 [[1.000e+00 3.370e+02 1.180e+02 ... 5.671e+03 5.671e+03 7.336e+03]
 [2.000e+00 3.240e+02 1.070e+02 ... 9.009e+03 9.009e+03 5.142e+03]
 [3.000e+00 3.160e+02 1.040e+02 ... 8.884e+03 8.884e+03 5.222e+03]
 ...
 [3.980e+02 3.300e+02 1.160e+02 ... 7.402e+03 7.402e+03 8.020e+03]
 [3.990e+02 3.120e+02 1.030e+02 ... 9.711e+03 9.711e+03 7.810e+03]
 [4.000e+02 3.330e+02 1.170e+02 ... 9.154e+03 9.154e+03 9.318e+03]]

The number of students with scholarship more then $9000:  88


In [42]:
# Task 6
sch_ind=np.where(adm[:,9]>9000)
print('The SOP and LOR scores of all student with scholarship more then $9000\n ',adm[sch_ind,4:6])

The SOP and LOR scores of all student with scholarship more then $9000
  [[[4.  4.5]
  [4.5 3. ]
  [3.  4. ]
  [3.5 3. ]
  [4.  4.5]
  [3.5 2.5]
  [4.  3. ]
  [3.  2. ]
  [5.  5. ]
  [2.  2. ]
  [3.  4.5]
  [5.  5. ]
  [2.5 2. ]
  [4.5 4. ]
  [1.5 3.5]
  [3.  2. ]
  [3.  3.5]
  [5.  5. ]
  [4.5 3.5]
  [3.  3. ]
  [4.  4. ]
  [3.5 3.5]
  [3.5 3. ]
  [3.5 4.5]
  [4.  3.5]
  [4.  3.5]
  [3.  3.5]
  [4.  3. ]
  [2.5 2. ]
  [3.5 3. ]
  [4.  4.5]
  [4.  4.5]
  [4.5 3. ]
  [4.5 4. ]
  [3.  3. ]
  [3.5 3. ]
  [4.5 4. ]
  [2.  4. ]
  [4.  4.5]
  [4.5 4.5]
  [3.  3. ]
  [3.5 3. ]
  [4.5 4.5]
  [4.  4.5]
  [2.5 3. ]
  [3.5 4. ]
  [5.  4. ]
  [4.5 5. ]
  [3.  3.5]
  [2.5 2.5]
  [3.5 3. ]
  [4.  4.5]
  [4.  4.5]
  [4.  4. ]
  [3.  2.5]
  [2.  2.5]
  [4.5 5. ]
  [1.5 2. ]
  [1.5 1.5]
  [5.  4.5]
  [4.  4.5]
  [1.5 2. ]
  [3.5 3. ]
  [4.  4.5]
  [2.5 2. ]
  [3.5 3.5]
  [3.5 3. ]
  [4.5 4.5]
  [3.5 3. ]
  [1.5 2. ]
  [5.  5. ]
  [1.5 2. ]
  [3.  3.5]
  [3.5 2.5]
  [3.5 4. ]
  [2.5 2. ]
  [4.  3.5]
  [

In [60]:
# Task 7
adm_ind=np.where((adm[:,1]>315)&(adm[:,2]>115)&(adm[:,7]==1))
print('The number of student with GRE greater then 315 TOEFL greater then 115 with reseach expereince:',np.size(adm_ind))
print ('\nThe serial number of the sudent :\n',adm[adm_ind,0])
adm[adm_ind,9]=1000
print('\nThe updated scholarship data:\n',adm[adm_ind,0:10:9])

The number of student with GRE greater then 315 TOEFL greater then 115 with reseach expereince: 41

The serial number of the sudent :
 [[  1.  23.  24.  25.  26.  33.  53.  71.  82.  98.  99. 108. 109. 121.
  122. 130. 139. 142. 144. 149. 152. 172. 177. 188. 194. 203. 204. 213.
  214. 215. 216. 260. 286. 287. 326. 338. 362. 373. 386. 398. 400.]]

The updated scholarship data:
 [[[   1. 1000.]
  [  23. 1000.]
  [  24. 1000.]
  [  25. 1000.]
  [  26. 1000.]
  [  33. 1000.]
  [  53. 1000.]
  [  71. 1000.]
  [  82. 1000.]
  [  98. 1000.]
  [  99. 1000.]
  [ 108. 1000.]
  [ 109. 1000.]
  [ 121. 1000.]
  [ 122. 1000.]
  [ 130. 1000.]
  [ 139. 1000.]
  [ 142. 1000.]
  [ 144. 1000.]
  [ 149. 1000.]
  [ 152. 1000.]
  [ 172. 1000.]
  [ 177. 1000.]
  [ 188. 1000.]
  [ 194. 1000.]
  [ 203. 1000.]
  [ 204. 1000.]
  [ 213. 1000.]
  [ 214. 1000.]
  [ 215. 1000.]
  [ 216. 1000.]
  [ 260. 1000.]
  [ 286. 1000.]
  [ 287. 1000.]
  [ 326. 1000.]
  [ 338. 1000.]
  [ 362. 1000.]
  [ 373. 1000.]
  [ 386. 100

ADDITIONAL QUESTIONS

In [62]:
# Task 8
cgpa_ind=np.where((adm[:,6]>=8.0)&(adm[:,6]<=8.5))
print('The number of student with CGPA scores from 8.0 to 8.5 :',np.count_nonzero(cgpa_ind))

The number of student with CGPA scores from 8.0 to 8.5 : 122


In [65]:
# Task 9
avg_sop=np.mean(adm[0:51,4])
print('The average SOP score of first 50 applicants:',avg_sop)
avg_lop=np.mean(adm[0:51,5])
print('The average LOP score of first 50 applicants:',avg_lop)
incease=((avg_sop-avg_lop)/avg_lop)*100
if avg_sop>avg_lop:
    print('Yes, SOP is more then LOP by :',incease,'%')
else:
    print('No')

The average SOP score of first 50 applicants: 3.5294117647058822
The average LOP score of first 50 applicants: 3.450980392156863
Yes, SOP is more then LOP by : 2.2727272727272645 %


In [96]:
# Task 10
quant1=['Q0','Q1','Q2','Q3','Q4']
quant=np.quantile(adm[:,9],(0,0.25,0.5,0.75,1))
print('Quantile\n',quant1,'\n',quant)
inq_r=(np.quantile(adm[:,9],0.75))- (np.quantile(adm[:,9],0.25))
print('Inner Quantile range = ',inq_r)
Q2=np.quantile(adm[:,9],0.25)
Q3=np.quantile(adm[:,9],0.75)
dev=inq_r*1.5
print('\nLower Fence = ',Q2-dev)
print('\nUpper Fence = ',Q3+dev)
Max=np.max(adm[:,9])
Min=np.min(adm[:,9])
print('\nMaximum = ',Max,'\nMinimum',Min)
Mean=np.mean(adm[:,9])
print('\nMean = ',Mean)
Range=Max-Min
print('\nRange = ',Range)
Median=np.median(adm[:,9])
print('\nMedian = ',Median)
standard_deviation=np.std(adm[:,9])
print('\nStandard Deviation = ',standard_deviation)
ind=np.where((adm[:,9]>12695.5)|(adm[:,9]<1987.5))
print('Number of outliers : ',np.size(ind))
print('Outliers:\n',adm[ind,9])

Quantile
 ['Q0', 'Q1', 'Q2', 'Q3', 'Q4'] 
 [1000. 6003. 7331. 8680. 9991.]
Inner Quantile range =  2677.0

Lower Fence =  1987.5

Upper Fence =  12695.5

Maximum =  9991.0 
Minimum 1000.0

Mean =  6936.2575

Range =  8991.0

Median =  7331.0

Standard Deviation =  2417.4462219858688
Number of outliers :  41
Outliers:
 [[1000. 1000. 1000. 1000. 1000. 1000. 1000. 1000. 1000. 1000. 1000. 1000.
  1000. 1000. 1000. 1000. 1000. 1000. 1000. 1000. 1000. 1000. 1000. 1000.
  1000. 1000. 1000. 1000. 1000. 1000. 1000. 1000. 1000. 1000. 1000. 1000.
  1000. 1000. 1000. 1000. 1000.]]


In [97]:
# Task 11
ch_ind=np.where(adm[:,8]>=0.95)
print('GRE score for have at least 95% cahnces of admission:\n',adm[ch_ind,1])
print('TOEFL score for have at least 95% cahnces of admission:\n',adm[ch_ind,2])
print('CGPA for have at least 95% cahnces of admission:\n',adm[ch_ind,6])

GRE score for have at least 95% cahnces of admission:
 [[334. 336. 336. 340. 339. 340. 339. 340. 334. 338. 333. 336. 340. 335.
  333.]]
TOEFL score for have at least 95% cahnces of admission:
 [[119. 119. 112. 120. 114. 120. 116. 120. 120. 120. 119. 119. 113. 117.
  117.]]
CGPA for have at least 95% cahnces of admission:
 [[9.7  9.8  9.76 9.5  9.76 9.92 9.8  9.91 9.87 9.66 9.78 9.62 9.74 9.82
  9.66]]
