# Creating and Manipulating NumPy Arrays

In [1]:
import numpy as np

In [3]:
# Task 1

hr=np.arange(1,501)
finance=np.arange(501,1001)
it=np.arange(1001,1501)
sales=np.arange(1501,2001)
print('Department HR\n',hr,'\n\n')
print('Department Finance\n',finance,'\n\n')
print('Department IT\n',it,'\n\n')
print('Department Sales\n',sales,'\n\n')

Department HR
 [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243

In [12]:
# Task 2
#salary for HR
print('Annual Salary of HR Department Employees')
print('number of employees in HR department: ',hr.size)
sal_hr=np.random.randint(25000,50000,500)
print('\nSalary for HR department employees:\n ',sal_hr)

#salary for Finance
print('\nAnnual Salary of Finance Department Employees')
print('number of employees in Finance department: ',finance.size)
sal_finance=sal_hr*1.25
print('\nSalary for Finance department employees:\n ',sal_finance)

#salary for  Sales
print('\nAnnual Salary of Sales Department Employees')
print('number of employees in Sales department: ',sales.size)
sal_sales=sal_finance*0.5
print('\nSalary for Sales department employees:\n ',sal_sales)

#salary for IT
print('\nAnnual Salary of IT Department Employees')
print('number of employees in IT department: ',it.size)
sal_it=sal_hr+5000
print('\nSalary for Sales department employees:\n ',sal_it)



Annual Salary of HR Department Employees
number of employees in HR department:  500

Salary for HR department employees:
  [41408 32386 37018 35575 32386 48593 38611 48554 42800 42968 40228 49310
 40870 28023 45552 46852 25641 40375 30710 38639 36444 39432 32827 37163
 34477 34643 39986 43093 28868 27468 28211 27066 46826 42326 34993 27332
 38704 25818 31780 33571 39769 27287 26269 40665 46087 38611 40278 48449
 25616 44138 48630 26460 43033 30500 37609 26589 30767 38493 42623 38044
 30692 27799 32767 29940 32228 38483 31702 40252 26738 27967 35262 32060
 29916 45738 40384 30410 44718 42797 27595 44532 32949 47634 30548 41522
 33295 45785 42554 42736 43125 31157 42843 25006 44949 48488 36050 38914
 35506 35107 31020 45873 29276 36832 42025 47890 37823 30264 42791 44260
 30493 35063 40914 34616 41616 33355 38914 38454 44962 49594 43410 48391
 29240 41982 44645 49977 43369 48202 42908 33686 42468 38511 32525 28162
 25140 30799 41483 45383 33845 41056 33363 29413 32056 28922 47275 29078
 

In [27]:
# Task 3
hrdep_comp=sal_hr.sum()
print('HR Department total expences: ',hrdep_comp)
findep_comp=sal_finance.sum()
print('Finance Department total expences: ',findep_comp)
saldep_comp=sal_sales.sum()
print('Sales Department total expences: ',saldep_comp)
itdep_comp=sal_it.sum()
print('IT Department total expences: ',itdep_comp)

total_comp=np.array([hrdep_comp,findep_comp,saldep_comp,itdep_comp])
maximum=total_comp.max()
print('The department costing more by amount:',total_comp.max())

dic_comp={'hr':hrdep_comp,'Finance':findep_comp,'Sales':saldep_comp,'IT':itdep_comp}
for x in dic_comp:
    if dic_comp[x]==maximum:
        print('Department costing more to the company is',x)

HR Department total expences:  18804151
Finance Department total expences:  23505188.75
Sales Department total expences:  11752594.375
IT Department total expences:  21304151
The department costing more by amount: 23505188.75
Department costing more to the company is Finance


In [37]:
# Task 4
tsal_hr=np.sort(sal_hr)[-1:-11:-1]
print('Top 10 of HR Department:\n',tsal_hr)
print('The Sum of Top 10 of HR Department:',tsal_hr.sum())

tsal_fin=np.sort(sal_finance)[-1:-11:-1]
print('\nTop 10 of Finance Department:\n',tsal_fin)
print('The Sum of Top 10 of Finance Department:',tsal_fin.sum())

tsal_sales=np.sort(sal_sales)[-1:-11:-1]
print('\nTop 10 of Sales Department:\n',tsal_sales)
print('The Sum of Top 10 of Sales Department:',tsal_sales.sum())

tsal_it=np.sort(sal_it)[-1:-11:-1]
print('\nTop 10 of IT Department:\n',tsal_it)
print('The Sum of Top 10 of IT Department:',tsal_it.sum())


Top 10 of HR Department:
 [49994 49983 49982 49977 49974 49901 49900 49893 49866 49818]
The Sum of Top 10 of HR Department: 499288

Top 10 of Finance Department:
 [62492.5  62478.75 62477.5  62471.25 62467.5  62376.25 62375.   62366.25
 62332.5  62272.5 ]
The Sum of Top 10 of Finance Department: 624110.0

Top 10 of Sales Department:
 [31246.25  31239.375 31238.75  31235.625 31233.75  31188.125 31187.5
 31183.125 31166.25  31136.25 ]
The Sum of Top 10 of Sales Department: 312055.0

Top 10 of IT Department:
 [54994 54983 54982 54977 54974 54901 54900 54893 54866 54818]
The Sum of Top 10 of IT Department: 549288


In [53]:
# Task 5
print('The count of the employees with salary greater in HR :',np.count_nonzero(sal_hr>45000))
print('The count of the employees with salary greater in Finance :',np.count_nonzero(sal_finance>45000))
print('The count of the employees with salary greater in Sales :',np.count_nonzero(sal_sales>45000))
print('The count of the employees with salary greater in IT :',np.count_nonzero(sal_it>45000))
abc_sal=np.append(sal_hr,sal_finance)
abc_sal=np.append(abc_sal,sal_it)
abc_sal=np.append(abc_sal,sal_sales)
print(abc_sal)
print('\nThe count of the employees with salary greater :',np.count_nonzero(abc_sal>45000))
abc_sal=abc_sal*1.1
print('\nThe salary increamented by 10% \n',abc_sal)

The count of the employees with salary greater in HR : 97
The count of the employees with salary greater in Finance : 280
The count of the employees with salary greater in Sales : 0
The count of the employees with salary greater in IT : 202
[41408.    32386.    37018.    ... 16570.625 24395.625 30332.5  ]

The count of the employees with salary greater : 579

The salary increamented by 10% 
 [45548.8    35624.6    40719.8    ... 18227.6875 26835.1875 33365.75  ]


In [60]:
# Task 6
index=np.where(sal_sales<20000)# index 
inc_salsales=sal_sales[index]
inc_salsales=inc_salsales*1.2
x_salsales=np.delete(sal_sales,(index))
inc_salsales=np.append(x_salsales,inc_salsales)
print('The new sale salary\n',inc_salsales)
print('The size of the salary :',inc_salsales.size)
print(sal_sales)
sal_sales=inc_salsales.copy()
print(sal_sales)



The new sale salary
 [25880.    20241.25  23136.25  22234.375 20241.25  30370.625 24131.875
 30346.25  26750.    26855.    25142.5   30818.75  25543.75  28470.
 29282.5   25234.375 24149.375 22777.5   24645.    20516.875 23226.875
 21548.125 21651.875 24991.25  26933.125 29266.25  26453.75  21870.625
 24190.    20981.875 24855.625 25415.625 28804.375 24131.875 25173.75
 30280.625 27586.25  30393.75  26895.625 23505.625 24058.125 26639.375
 23777.5   20479.375 20142.5   24051.875 25157.5   22038.75  20037.5
 28586.25  25240.    27948.75  26748.125 27832.5   20593.125 29771.25
 25951.25  20809.375 28615.625 26596.25  26710.    26953.125 26776.875
 28093.125 30305.    22531.25  24321.25  22191.25  21941.875 28670.625
 23020.    26265.625 29931.25  23639.375 26744.375 27662.5   21914.375
 25571.25  21635.    26010.    20846.875 24321.25  24033.75  28101.25
 30996.25  27131.25  30244.375 26238.75  27903.125 31235.625 27105.625
 30126.25  26817.5   21053.75  26542.5   24069.375 20328.125 259

In [62]:
# Task 7
index=np.where(sales>=1996)
sales=np.delete(sales,(index))
sales_1=np.arange(2001,2006)
sales=np.append(sales,sales_1)
print('The last ten enteries:',sales[-1:-11:-1])

The last ten enteries: [2005 2004 2003 2002 2001 1995 1994 1993 1992 1991]


ADDITIONAL QUESTION

In [65]:
# Task 8
avg_hr=sal_hr.mean()
avg_sales=sal_sales.mean()
print('average salary of hr department: ',avg_hr)
print('average salary of sales department: ',avg_sales)
dif_avg=avg_hr-avg_sales
if avg_hr>avg_sales:
    print('average salary of hr more the average salary of sales by :',dif_avg)
else:
    print('average salary of sales more the average salary of hr by :',dif_avg)



average salary of hr department:  37608.302
average salary of sales department:  24491.214
average salary of hr more the average salary of sales by : 13117.088000000003


In [67]:
# Task 9
print('the number of employees getting salary between 50000 to 55000 USD: ')
np.count_nonzero((sal_finance>=50000)&(sal_finance<=55000))

the number of employees getting salary between 50000 to 55000 USD: 


93

In [79]:
# Task 10
from numpy import genfromtxt
emp_code=genfromtxt('DS1_C4_S1_Numpy_PracticeBrief.csv',delimiter=',',skip_header=1) 
print(emp_code)
emp_code1=emp_code[:,1]
print('Average age:',emp_code1.mean())

[[ 1. 22.]
 [ 2. 27.]
 [ 3. 31.]
 [ 4. 29.]
 [ 5. 27.]
 [ 6. 26.]
 [ 7. 27.]
 [ 8. 23.]
 [ 9. 27.]
 [10. 32.]
 [11. 28.]
 [12. 27.]
 [13. 22.]
 [14. 27.]
 [15. 35.]
 [16. 33.]
 [17. 28.]
 [18. 22.]
 [19. 25.]
 [20. 27.]
 [21. 37.]
 [22. 27.]
 [23. 24.]
 [24. 27.]
 [25. 28.]
 [26. 26.]
 [27. 27.]
 [28. 27.]
 [29. 29.]
 [30. 49.]
 [31. 26.]
 [32. 32.]
 [33. 26.]
 [34. 24.]
 [35. 24.]
 [36. 23.]
 [37. 28.]
 [38. 28.]
 [39. 22.]
 [40. 26.]
 [41. 32.]
 [42. 35.]
 [43. 33.]
 [44. 31.]
 [45. 30.]
 [46. 36.]
 [47. 22.]
 [48. 23.]
 [49. 32.]
 [50. 34.]]
Average age: 28.26


In [82]:
# Task 11
print('Total number of employees having age more then 25: ',np.count_nonzero(emp_code[:,1]>25))

Total number of employees having age more then 25:  38


In [85]:
# Task 12
print('All the employees with age between 30 and 35\n')
index=np.where((emp_code[:,1]>30)&(emp_code[:,1]<35))
print(emp_code[index,:])

All the employees with age between 30 and 35

[[[ 3. 31.]
  [10. 32.]
  [16. 33.]
  [32. 32.]
  [41. 32.]
  [43. 33.]
  [44. 31.]
  [49. 32.]
  [50. 34.]]]
