In [1]:
import numpy as np

In [2]:
import tensorflow as tf
from tensorflow import keras

**TASK 1**

In [3]:
tf.strings.join(['1045','chandler','chandler@friend.com','9876543210','newyork','M','17/09/1996'],separator="~")

<tf.Tensor: shape=(), dtype=string, numpy=b'1045~chandler~chandler@friend.com~9876543210~newyork~M~17/09/1996'>

**TASK 2**

In [4]:
t=tf.constant(np.array(['indigo','violet','programmer','computer','training','kitchen','array','instagram','bluetooth']).reshape(3,3))
t

<tf.Tensor: shape=(3, 3), dtype=string, numpy=
array([[b'indigo', b'violet', b'programmer'],
       [b'computer', b'training', b'kitchen'],
       [b'array', b'instagram', b'bluetooth']], dtype=object)>

**TASK 3**

In [5]:
Product_Price=tf.constant(1895.2)
print(Product_Price)
new=tf.constant(1895.2,tf.float16)
print(new)

tf.Tensor(1895.2, shape=(), dtype=float32)
tf.Tensor(1895.0, shape=(), dtype=float16)


**TASK 4**

In [6]:
mark = np.round(np.random.uniform(100,200,15).reshape(-1,3),5 )
marks= tf.constant(mark,tf.int16)
marks

<tf.Tensor: shape=(5, 3), dtype=int16, numpy=
array([[150, 137, 101],
       [142, 169, 187],
       [194, 157, 130],
       [170, 187, 165],
       [118, 178, 102]], dtype=int16)>

In [7]:
total=tf.Variable(marks)
print(total)
for x in range(len(marks)):
  for y in range(len(marks[x])):
    total[x,y].assign(np.random.randint(100,200))
print(total)

<tf.Variable 'Variable:0' shape=(5, 3) dtype=int16, numpy=
array([[150, 137, 101],
       [142, 169, 187],
       [194, 157, 130],
       [170, 187, 165],
       [118, 178, 102]], dtype=int16)>
<tf.Variable 'Variable:0' shape=(5, 3) dtype=int16, numpy=
array([[170, 117, 197],
       [148, 105, 113],
       [102, 114, 126],
       [105, 172, 166],
       [116, 197, 102]], dtype=int16)>


**TASK 5**

**TASK 6**

In [8]:
t_currency = {'india':'rupee', 'america':'dollar','eurpoe':'euro'}
t_currency

currency_keys = tf.convert_to_tensor(list(t_currency.keys()))
print(currency_keys)
currency_values = tf.convert_to_tensor(list(t_currency.values()))
print(currency_values)


tf.Tensor([b'india' b'america' b'eurpoe'], shape=(3,), dtype=string)
tf.Tensor([b'rupee' b'dollar' b'euro'], shape=(3,), dtype=string)


**TASK 7**

In [9]:
unit=tf.constant(np.random.randint(1,10,4).reshape(2,2))
unit_price=tf.constant(np.random.randint(100,200,4).reshape(2,2))
print(unit,unit_price)
grand_price=unit*unit_price
print(grand_price)
grand_total=sum(np.array(grand_price).reshape(-1))
print(grand_total)

tf.Tensor(
[[1 2]
 [9 9]], shape=(2, 2), dtype=int64) tf.Tensor(
[[193 181]
 [153 131]], shape=(2, 2), dtype=int64)
tf.Tensor(
[[ 193  362]
 [1377 1179]], shape=(2, 2), dtype=int64)
3111
